# Generated by Django 5.0.6 on 2024-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
