# Generated by Django 5.0.6 on 2024-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='points',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.5, null=True),
        ),
    ]
