# Generated by Django 5.0.6 on 2024-07-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_options_points_question_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Updated_at',
            new_name='updated_at',
        ),
    ]
